export const ADD_USER = "ADD_USER";

export const USER_CONFIRM_COMPLETION = "USER_CONFIRM_COMPLETION";

export const SIGN_OUT_USER = "SIGN_OUT_USER";

export const GET_BY_TOKEN_SUCCESS = "GET_BY_TOKEN_SUCCESS";

export const GET_BY_TOKEN_STARTED = "GET_BY_TOKEN_STARTED";

export const GET_BY_TOKEN_FAILURE = "GET_BY_TOKEN_FAILURE";

export const USER_CREATE_SUCCESS = "USER_CREATE_SUCCESS";

export const USER_CREATE_STARTED = "USER_CREATE_STARTED";

export const USER_CREATE_FAILURE = "USER_CREATE_FAILURE";

export const USER_UPDATE_SUCCESS = "USER_UPDATE_SUCCESS";

export const USER_UPDATE_STARTED = "USER_UPDATE_STARTED";

export const USER_UPDATE_FAILURE = "USER_UPDATE_FAILURE";

export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";

export const USER_LOGIN_STARTED = "USER_LOGIN_STARTED";

export const USER_LOGIN_FAILURE = "USER_LOGIN_FAILURE";

export const ADD_FAVORITES_SUCCESS = "ADD_FAVORITES_SUCCESS";

export const ADD_FAVORITES_STARTED = "ADD_FAVORITES_STARTED";

export const ADD_FAVORITES_FAILURE = "ADD_FAVORITES_FAILURE";

export const ADD_SHOPLIST_SUCCESS = "ADD_SHOPLIST_SUCCESS";

export const ADD_SHOPLIST_STARTED = "ADD_SHOPLIST_STARTED";

export const ADD_SHOPLIST_FAILURE = "ADD_SHOPLIST_FAILURE";

export const ADD_BOOKS = "ADD_BOOKS";

export const BOOKS_CONFIRM_COMPLETION = "BOOKS_CONFIRM_COMPLETION";

export const BOOKS_FETCH_SUCCESS = "BOOKS_FETCH_SUCCESS";

export const BOOKS_FETCH_STARTED = "BOOKS_FETCH_STARTED";

export const BOOKS_FETCH_FAILURE = "BOOKS_FETCH_FAILURE";

export const BOOK_FETCH_SUCCESS = "BOOK_FETCH_SUCCESS";

export const BOOK_FETCH_STARTED = "BOOK_FETCH_STARTED";

export const BOOK_FETCH_FAILURE = "BOOK_FETCH_FAILURE";

export const BOOK_CREATE_SUCCESS = "BOOK_CREATE_SUCCESS";

export const BOOK_CREATE_STARTED = "BOOK_CREATE_STARTED";

export const BOOK_CREATE_FAILURE = "BOOK_CREATE_FAILURE";

export const BOOK_CHANGE_SUCCESS = "BOOK_CHANGE_SUCCESS";

export const BOOK_CHANGE_STARTED = "BOOK_CHANGE_STARTED";

export const BOOK_CHANGE_FAILURE = "BOOK_CHANGE_FAILURE";

export const ADD_REVIEW_SUCCESS = "ADD_REVIEW_SUCCESS";

export const ADD_REVIEW_STARTED = "ADD_REVIEW_STARTED";

export const ADD_REVIEW_FAILURE = "ADD_REVIEW_FAILURE";

export const GET_REVIEWS_SUCCESS = "GET_REVIEWS_SUCCESS";

export const GET_REVIEWS_STARTED = "GET_REVIEWS_STARTED";

export const GET_REVIEWS_FAILURE = "GET_REVIEWS_FAILURE";

export const GENRES_FETCH_SUCCESS = "GENRES_FETCH_SUCCESS";

export const GENRES_FETCH_STARTED = "GENRES_FETCH_STARTED";

export const GENRES_FETCH_FAILURE = "GENRES_FETCH_FAILURE";
