export const ADD_USER = "ADD_USER";

export const USER_CONFIRM_COMPLETION = "USER_CONFIRM_COMPLETION";

export const SIGN_OUT_USER = "SIGN_OUT_USER";

export const GET_BY_TOKEN_FINISH = "GET_BY_TOKEN_FINISH";

export const GET_BY_TOKEN_STARTED = "GET_BY_TOKEN_STARTED";

export const USER_CREATE_FINISH = "USER_CREATE_FINISH";

export const USER_CREATE_STARTED = "USER_CREATE_STARTED";

export const USER_UPDATE_FINISH = "USER_UPDATE_FINISH";

export const USER_UPDATE_STARTED = "USER_UPDATE_STARTED";

export const USER_LOGIN_FINISH = "USER_LOGIN_FINISH";

export const USER_LOGIN_STARTED = "USER_LOGIN_STARTED";

export const ADD_FAVORITES_FINISH = "ADD_FAVORITES_FINISH";

export const ADD_FAVORITES_STARTED = "ADD_FAVORITES_STARTED";

export const ADD_SHOPLIST_FINISH = "ADD_SHOPLIST_FINISH";

export const ADD_SHOPLIST_STARTED = "ADD_SHOPLIST_STARTED";

export const ADD_BOOKS = "ADD_BOOKS";

export const BOOKS_CONFIRM_COMPLETION = "BOOKS_CONFIRM_COMPLETION";

export const BOOKS_FETCH_FINISH = "BOOKS_FETCH_FINISH";

export const BOOKS_FETCH_STARTED = "BOOKS_FETCH_STARTED";

export const BOOK_FETCH_FINISH = "BOOK_FETCH_FINISH";

export const BOOK_FETCH_STARTED = "BOOK_FETCH_STARTED";

export const BOOK_CREATE_FINISH = "BOOK_CREATE_FINISH";

export const BOOK_CREATE_STARTED = "BOOK_CREATE_STARTED";

export const BOOK_CHANGE_FINISH = "BOOK_CHANGE_FINISH";

export const BOOK_CHANGE_STARTED = "BOOK_CHANGE_STARTED";

export const ADD_REVIEW_FINISH = "ADD_REVIEW_FINISH";

export const ADD_REVIEW_STARTED = "ADD_REVIEW_STARTED";

export const GET_REVIEWS_FINISH = "GET_REVIEWS_FINISH";

export const GET_REVIEWS_STARTED = "GET_REVIEWS_STARTED";

export const GENRES_FETCH_FINISH = "GENRES_FETCH_FINISH";

export const GENRES_FETCH_STARTED = "GENRES_FETCH_STARTED";
